### ISSUE TITLE
[feature] Configuration file to toggle specific slots or aspects

### ISSUE THREAD

**Issue by bideco** [Dogloverblue17/Nerf-Keep-Inventory#1]
Being able to toggle a few of the different parts of this plugin would improve it considerably in my opinion.

Being able to enable and disable the dropping of hotbar slots, offhand slots, armour slots, and named items individually seems like a no brainer for this type of plugin, but I'm not sure how feasible it is for you to implement. 

Just a suggestion. Otherwise, I love the idea and goal of the plugin. Good work.

**Comment by lBleyl** [comment]
I agree with you, especially EXP, losing some items is frustrating on my server, but EXP is essential to lose.

**Comment by lBleyl** [comment]
being able to toggle EXP lose on death please.
